const {JSDOM}=require('jsdom');const fs=require('fs');
const H=fs.readFileSync(require('path').join(__dirname,'../public/index.html'),'utf8');
const D=JSON.parse(H.match(/window\.__DATA__=(\[[\s\S]*?\]);<\/script>/)[1].replace(/\\u003c/g,'<').replace(/\\u003e/g,'>'));
const ctx=()=>new Proxy({},{get:(t,k)=>{if(k==='measureText')return s=>({width:20});
 if(['font','fillStyle','strokeStyle','lineWidth','textAlign','textBaseline'].includes(k))return t[k]||'';return ()=>{}},set:(t,k,v)=>{t[k]=v;return true}});
const errs=[];const dom=new JSDOM(H,{runScripts:'dangerously',pretendToBeVisual:true,beforeParse(w){
 w.HTMLCanvasElement.prototype.getContext=()=>ctx();
 w.Element.prototype.getBoundingClientRect=()=>({left:0,top:0,width:900,height:320,right:900,bottom:320});
 Object.defineProperty(w.HTMLElement.prototype,'clientWidth',{get(){return 900}});
 Object.defineProperty(w.HTMLElement.prototype,'clientHeight',{get(){return 320}});
 w.HTMLElement.prototype.scrollIntoView=()=>{};w.scrollTo=()=>{};w.addEventListener('error',e=>errs.push(e.message));}});
const w=dom.window,d=w.document;
const med=a=>{a=[...a].sort((x,y)=>x-y);const n=a.length;return n?(n%2?a[(n-1)/2]:(a[n/2-1]+a[n/2])/2):null};
let NG=0;const ng=m=>{console.log('  NG '+m);NG++};
setTimeout(()=>{
 const B=D.filter(x=>x.a!=='XX');
 const O=['NBF','JRE','GOR','DOI','ICG','JEI','MHR','JPR','TRE','HLC','NUD','HFR','SHR','MTR','SKR','KDX','CTR','ORI'];
 const bs=[...d.querySelectorAll('#segScope button')];
 console.log('【1】法人ラベルの網羅');
 O.forEach(l=>{if(!H.includes(l+":'"))ng('CORP_Lに'+l+'がない')});
 console.log('  18法人すべて定義済み');
 console.log('【2】各プルダウン・凡例の法人数');
 [...d.querySelectorAll('#bnav button')][2].click();
 const pc=d.getElementById('prCorp');
 let s1=0;[...pc.options].slice(1).forEach(o=>{const m=o.textContent.match(/（(\d+)）/);if(m)s1+=+m[1]});
 const OF=B.filter(x=>x.u==='OF');
 if(s1!==OF.length)ng('物件タブの法人合計 '+s1+' ≠ '+OF.length);
 [...d.querySelectorAll('#bnav button')][3].click();
 const vc=d.getElementById('vCorp');
 let s2=0;[...vc.options].slice(1).forEach(o=>{const m=o.textContent.match(/（(\d+)）/);if(m)s2+=+m[1]});
 const EL=B.filter(x=>!x.pt&&x.yra!=null&&x.yna!=null&&x.oer!=null&&x.ug!=null&&x.ap!=null&&x.u==='OF');
 if(s2!==EL.length)ng('評価タブの法人合計 '+s2+' ≠ '+EL.length);
 console.log('  物件'+s1+'／評価'+s2+' 一致');
 console.log('【3】戦略プルダウン');
 [...d.querySelectorAll('#bnav button')][0].click();
 const st=d.getElementById('selStrat');
 if(st.options.length!==18)ng('戦略が18法人でない: '+st.options.length);
 console.log('  '+st.options.length+'法人');
 console.log('【4】全物件の評価カード');
 [...d.querySelectorAll('#bnav button')][3].click();
 let bad=0,tot=0;
 [0,1].forEach(i=>{bs[i].click();const s=d.getElementById('vSel');
  [...s.options].slice(1).forEach(o=>{s.value=o.value;s.dispatchEvent(new w.Event('change'));tot++;
   const t=d.getElementById('valCard').textContent;
   if(/undefined|NaN/.test(t))bad++;
   const m=t.match(/(\d+)物件中 (\d+)位/);
   if(!m||+m[2]<1||+m[2]>+m[1])bad++;});});
 if(bad)ng('評価カードの不整合 '+bad+'/'+tot);
 console.log('  '+tot+'物件 異常'+bad);
 console.log('【5】全ビュー巡回');
 let e0=errs.length,b2=0,n=0;
 [0,1].forEach(i=>{bs[i].click();
  [...d.querySelectorAll('#bnav button')].forEach(b=>{b.click();
   [...d.querySelectorAll('#subtabs button')].forEach(x=>x.click());
   [...d.querySelectorAll('.view.on .seg button, .pane.on .seg button')].forEach(x=>{x.click();n++;
    const t=d.querySelector('.view.on').textContent;
    if(/undefined|NaN|null|n=0\)/.test(t))b2++;});});});
 if(b2)ng('異常表記 '+b2);
 if(errs.length>e0)ng('実行時エラー '+(errs.length-e0));
 console.log('  '+n+'操作 異常'+b2);
 console.log('\n=== 全体整合: 要修正 '+NG+' 件 / エラー '+errs.length+' ===');if(NG||errs.length)process.exitCode=1;
},1000);
