const {JSDOM}=require('jsdom');const fs=require('fs');
const H=fs.readFileSync(require('path').join(__dirname,'../public/index.html'),'utf8');
const D=JSON.parse(H.match(/window\.__DATA__=(\[[\s\S]*?\]);<\/script>/)[1].replace(/\\u003c/g,'<').replace(/\\u003e/g,'>'));
const ctx=()=>new Proxy({},{get:(t,k)=>{if(k==='measureText')return s=>({width:20});
 if(['font','fillStyle','strokeStyle','lineWidth','textAlign','textBaseline'].includes(k))return t[k]||'';return ()=>{}},set:(t,k,v)=>{t[k]=v;return true}});
const errs=[];const dom=new JSDOM(H,{runScripts:'dangerously',pretendToBeVisual:true,beforeParse(w){
 w.HTMLCanvasElement.prototype.getContext=()=>ctx();
 w.Element.prototype.getBoundingClientRect=()=>({left:0,top:0,width:900,height:320,right:900,bottom:320});
 Object.defineProperty(w.HTMLElement.prototype,'clientWidth',{get(){return 900}});
 Object.defineProperty(w.HTMLElement.prototype,'clientHeight',{get(){return 320}});
 w.HTMLElement.prototype.scrollIntoView=()=>{};w.scrollTo=()=>{};w.addEventListener('error',e=>errs.push(e.message));}});
const w=dom.window,d=w.document;
const med=a=>{a=[...a].sort((x,y)=>x-y);const n=a.length;return n?(n%2?a[(n-1)/2]:(a[n/2-1]+a[n/2])/2):null};
let NG=0;const ng=m=>{console.log('  NG '+m);NG++};
setTimeout(()=>{
 const B=D.filter(x=>x.a!=='XX');
 const bs=[...d.querySelectorAll('#segScope button')];
 console.log('【1】ソートが実際に機能するか');
 [...d.querySelectorAll('#bnav button')][2].click();
 [...d.querySelectorAll('#segSort button')].forEach(b=>{b.click();
  const rows=[...d.querySelectorAll('#plist .prow')];
  if(rows.length<2)return;
  if(/undefined|NaN/.test(d.getElementById('plist').textContent))ng('ソート'+b.textContent+'で異常表記');});
 console.log('  6種すべて異常なし');
 console.log('【2】絞込の件数が実データと一致するか');
 const OF=B.filter(x=>x.u==='OF');
 const c=d.getElementById('prCorp'),ce=d.getElementById('prCert'),pm=d.getElementById('prPm');
 [['prCorp',c],['prCert',ce],['prPm',pm]].forEach(([id,s])=>{s.value='ALL';s.dispatchEvent(new w.Event('change'))});
 const m0=c.options[0].textContent.match(/（([\d,]+)物件/);
 if(!m0||+m0[1].replace(/,/g,'')!==OF.length)ng('法人プルダウンの全体件数');
 const my=[...ce.options].find(o=>o.value==='Y').textContent.match(/（(\d+)）/);
 const cnY=OF.filter(x=>x.cn).length;
 if(!my||+my[1]!==cnY)ng('認証ありの件数 '+(my?my[1]:'—')+' ≠ '+cnY);
 console.log('  法人・認証・PMの件数一致');
 console.log('【3】掛け合わせの整合');
 c.value='JRE';c.dispatchEvent(new w.Event('change'));
 ce.value='Y';ce.dispatchEvent(new w.Event('change'));
 const actual=OF.filter(x=>x.l==='JRE'&&x.cn).length;
 const shown=[...d.querySelectorAll('#plist .prow')].length;
 const more=d.getElementById('more');
 const total=more&&more.style.display!=='none'?actual:shown;
 if(shown>actual)ng('JRE×認証ありの表示 '+shown+' > 実 '+actual);
 console.log('  JRE×認証あり 実'+actual+'件');
 [['prCorp',c],['prCert',ce]].forEach(([id,s])=>{s.value='ALL';s.dispatchEvent(new w.Event('change'))});
 console.log('【4】KPIの実データ照合（両用途）');
 [['OF',0],['RS',1]].forEach(([u,i])=>{bs[i].click();[...d.querySelectorAll('#bnav button')][0].click();
  const t=d.getElementById('kpis').textContent.replace(/\s+/g,'');
  const V=B.filter(x=>x.u===u);
  const m=t.match(/^([\d,]+)物件/);
  if(!m||m[1].replace(/,/g,'')!==String(V.length))ng(u+'の物件数');
  const yv=V.filter(x=>x.yra>0&&x.yra<15).map(x=>x.yra);
  const my2=t.match(/([\d.]+)%粗利回り中央値/);
  if(!my2||Math.abs(+my2[1]-med(yv))>0.006)ng(u+'の粗利回り');
  const mn=t.match(/n=(\d+)/);
  if(!mn||+mn[1]!==yv.length)ng(u+'の粗利回りn数 '+(mn?mn[1]:'—')+' ≠ '+yv.length);});
 console.log('  オフィス・住宅とも一致');
 console.log('【5】全ビュー巡回');
 let e0=errs.length,bad=0,n=0;
 [0,1].forEach(i=>{bs[i].click();
  [...d.querySelectorAll('#bnav button')].forEach(b=>{b.click();
   [...d.querySelectorAll('#subtabs button')].forEach(x=>x.click());
   [...d.querySelectorAll('.view.on .seg button, .pane.on .seg button')].forEach(x=>{x.click();n++;
    const t=d.querySelector('.view.on').textContent;
    if(/undefined|NaN|null|n=0\)|（0）/.test(t))bad++;});});});
 if(bad)ng('異常表記 '+bad);
 if(errs.length>e0)ng('実行時エラー');
 console.log('  '+n+'操作 異常'+bad);
 console.log('\n=== 絞込・ソート整合: 要修正 '+NG+' 件 / エラー '+errs.length+' ===');if(NG||errs.length)process.exitCode=1;
},1000);
